version: '3.4'

services:
  quadro-tech-admin-dev:
    image: 
    container_name: 
    hostname: 
    restart: 
    networks:
      video_net:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=docker
    healthcheck:
     test: 
     interval: 5s
     timeout: 10s
     retries: 3
    ports:
      - 91:80


networks:
  video_net:
    driver: 
