version: '3.4'

services:
  sky-of-ukraine-back:
    image: 
    container_name: 
    hostname: 
    restart:
    networks:
      video_net:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=docker
    healthcheck:
     test:
     interval: 5s
     timeout: 10s
     retries: 3
    ports:
      - 89:80

  mysql:
    image: mysql:5.7
    volumes:

    hostname: 
    environment: 
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE:
    networks:
      video_net:

networks:
  video_net:
    driver: bridge
